# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-01 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='setor',
            table='crime_setor',
        ),
    ]
