# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-02 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_auto_20181002_1947'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='furto_crimes',
            table='furto_crimes',
        ),
        migrations.AlterModelTable(
            name='roubo_crimes',
            table='roubo_crimes',
        ),
        migrations.AlterModelTable(
            name='roubo_vcrimes',
            table='roubo_vcrimes',
        ),
        migrations.AlterModelTable(
            name='setor',
            table='setor',
        ),
    ]
