# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-02 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_auto_20181002_1949'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='furto_crimes',
            table='crime_furto_crimes',
        ),
        migrations.AlterModelTable(
            name='roubo_crimes',
            table='crime_roubo_crimes',
        ),
        migrations.AlterModelTable(
            name='roubo_vcrimes',
            table='crime_roubo_vcrimes',
        ),
        migrations.AlterModelTable(
            name='setor',
            table='crime_setor',
        ),
    ]
