# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-11 18:45
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_auto_20181002_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='furto_crimes',
            name='nomeCrime',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roubo_crimes',
            name='nomeCrime',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roubo_vcrimes',
            name='nomeCrime',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setor',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(default='none', srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setor',
            name='graph',
            field=models.CharField(default='none', max_length=750),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setor',
            name='nom_di',
            field=models.CharField(default='none', max_length=38),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setor',
            name='nom_mu',
            field=models.CharField(default='none', max_length=32),
            preserve_default=False,
        ),
    ]
