# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-11 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_auto_20181011_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='center',
        ),
    ]
