# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-11 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_remove_setor_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='graph',
        ),
    ]
